### ISSUE TITLE
Add Konsole port

### ISSUE THREAD

**Issue by Reiddragon** [embark-theme/embark-theme.github.io#5]
Hallo!
Really loved Embark, but there wasn't a port for Konsole... [so I made one!](https://github.com/Reiddragon/embark-konsole)
Just thought I'd open an issue to maybe make this official since Konsole is a pretty popular terminal emulator, so I'm sure there's someone out there looking to use it with Embark

**Comment by skbolton** [comment]
Created a Repo [here](https://github.com/embark-theme/Konsole) if you want to create a PR there
