### ISSUE TITLE
Pywal port

### ISSUE THREAD

**Issue by Reiddragon** [embark-theme/embark-theme.github.io#6]
Back again with [another port](https://github.com/Reiddragon/wal-themes/blob/master/dark/embark.json), this time for [Pywal](https://github.com/dylanaraps/pywal/)

This means Embark is now a thing on anything Pywal supports, like i3, Sway, dwm, Firefox, etc  

May not necessarily work as well as dedicated ports for some things (Vim for example works far better with the existing Embark port compared to the Pywal port), but for most things it works pretty well so I think it's worth adding to the collection.

![image](https://user-images.githubusercontent.com/40322297/223965684-9be7c0a6-7088-468c-b584-f535756b8183.png)

**Comment by skbolton** [comment]
Sorry @Reiddragon I missed this. The notifications kinda stuck when you move things to organizations...

I'll create a repo for it and you can pr whenever.

**Comment by skbolton** [comment]
https://github.com/embark-theme/pywal
